services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:  # Добавлено
      - mynet
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: calc-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calculator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:  # Добавлено
      - mynet

volumes:
  postgres_data:

networks:  # Добавлено
  mynet:
    driver: bridge